import { copyFile, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { artifacts } from "hardhat";

/**
 * Publishes the contract interface to the web app.
 *
 * Writes `web/src/abi/auctionHouse.ts` and `web/src/abi/demoNft.ts`, and copies
 * every `deployments/<chainId>.json` into `web/src/deployments/`.
 *
 * The `as const` on each ABI is not decoration. Without it, viem falls back to
 * generic `unknown` argument and return types and every call site loses its
 * type checking.
 *
 *   npm run export-abi
 */

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CONTRACTS_DIR = path.resolve(HERE, "..");
const DEPLOYMENTS_DIR = path.join(CONTRACTS_DIR, "deployments");
const WEB_SRC = path.resolve(CONTRACTS_DIR, "..", "web", "src");

/** Which artifacts to publish, and what to call the export in each file. */
const TARGETS = [
  { contract: "AuctionHouse", file: "auctionHouse.ts", export: "auctionHouseAbi" },
  { contract: "DemoNFT", file: "demoNft.ts", export: "demoNftAbi" },
] as const;

const abiDir = path.join(WEB_SRC, "abi");
const deploymentsOut = path.join(WEB_SRC, "deployments");
await mkdir(abiDir, { recursive: true });
await mkdir(deploymentsOut, { recursive: true });

for (const target of TARGETS) {
  const artifact = await artifacts.readArtifact(target.contract);

  const source = [
    "// Generated by contracts/scripts/export-abi.ts. Do not edit by hand.",
    `// Source: contracts/src/${target.contract}.sol`,
    "//",
    "// The `as const` is required: viem infers argument and return types from the",
    "// literal ABI, and a widened `Abi[]` silently degrades every call to `unknown`.",
    "",
    `export const ${target.export} = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    "",
  ].join("\n");

  const outFile = path.join(abiDir, target.file);
  await writeFile(outFile, source, "utf8");
  console.log(`ABI  ${target.contract.padEnd(13)} -> ${path.relative(CONTRACTS_DIR, outFile)}`);
}

let copied = 0;
try {
  for (const entry of await readdir(DEPLOYMENTS_DIR)) {
    if (!entry.endsWith(".json")) continue;
    const from = path.join(DEPLOYMENTS_DIR, entry);
    const to = path.join(deploymentsOut, entry);
    await copyFile(from, to);
    const record = JSON.parse(await readFile(from, "utf8"));
    console.log(
      `Deployment chain ${String(record.chainId).padEnd(6)} -> ${path.relative(CONTRACTS_DIR, to)}`,
    );
    copied += 1;
  }
} catch (error) {
  if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
}

if (copied === 0) {
  console.log("\nNo deployment records found. Run `npm run deploy` to create one.");
}
