// ---------------------------------------------------------------------------
// Where the indexer learns which addresses to watch, and from which block.
//
// The local chain is recreated on every start, so `contracts/deployments/
// 31337.json` is GENERATED by `npm run deploy --workspace contracts` and it is
// gitignored. That is why this file is imported rather than hard-coded: a
// hard-coded address is correct only while account 0 of the test mnemonic
// deploys at nonce 0 and 1, and it silently indexes an empty contract the
// moment anything else touches the chain first.
//
// The import is also what gives hot reload. Ponder watches every module in the
// import graph of ponder.config.ts, so re-running the deployer rewrites this
// record and Ponder restarts the indexing run against the new addresses
// without anybody touching the container.
//
// ORDER OF PRECEDENCE: environment first, then the record. The environment
// wins because compose already passes AUCTION_HOUSE_ADDRESS and
// DEMO_NFT_ADDRESS to the web service, and an operator who pins an address
// there means it.
// ---------------------------------------------------------------------------

import type { Address } from "viem";
import { getAddress, isAddress } from "viem";

import record from "../contracts/deployments/31337.json";

/**
 * Every shape the deployment record has been written in.
 *
 * `contracts/scripts/deploy.ts` nests the addresses under `contracts`, while
 * the copy that `export-abi.ts` writes for the browser flattens them to
 * `auctionHouse` / `demoNft`. Both are accepted here rather than picking one,
 * because the alternative is an indexer that starts, reports healthy and
 * indexes nothing at all when the writer changes. Every field is optional so
 * that a record missing a key fails loudly in `resolve()` below with a message
 * that names the key, instead of failing as `undefined` inside viem.
 */
type DeploymentRecord = {
  chainId?: number;
  blockNumber?: number;
  blockCreated?: number;
  auctionHouse?: string;
  demoNft?: string;
  contracts?: { AuctionHouse?: string; DemoNFT?: string };
};

const deployment = record as DeploymentRecord;

/** Reads one address from the environment, then the record. Never guesses. */
function resolveAddress(envName: string, fromRecord: string | undefined): Address {
  const raw = process.env[envName]?.trim() || fromRecord;

  if (!raw) {
    throw new Error(
      `${envName} is unset and contracts/deployments/31337.json carries no address for it. ` +
        "Run the deployer before the indexer: in Compose the `depends_on: deployer: " +
        "service_completed_successfully` gate does this, and on a host `npm run deploy` does.",
    );
  }
  if (!isAddress(raw)) {
    throw new Error(`${envName} is not an address: ${raw}`);
  }
  // Checksum it. Ponder compares addresses as lower-case strings internally,
  // but a checksummed value is what every other tool in this repo prints.
  return getAddress(raw);
}

export const auctionHouseAddress = resolveAddress(
  "AUCTION_HOUSE_ADDRESS",
  deployment.auctionHouse ?? deployment.contracts?.AuctionHouse,
);

export const demoNftAddress = resolveAddress(
  "DEMO_NFT_ADDRESS",
  deployment.demoNft ?? deployment.contracts?.DemoNFT,
);

/**
 * The block the contracts were deployed in.
 *
 * Starting at 0 would work but it makes every restart re-scan the whole chain.
 * On a chain that resets this is cheap, but `disableCache` (see
 * ponder.config.ts) means those blocks are fetched over RPC every single time,
 * and a seeded demo chain is thousands of blocks deep by the time anyone looks
 * at it. Falling back to 0 is deliberate: a record without a block number
 * should be slow, not wrong.
 */
export const startBlock = Number(
  process.env.PONDER_START_BLOCK ?? deployment.blockNumber ?? deployment.blockCreated ?? 0,
);

/** The chain id the record was written for. Used only to sanity-check config. */
export const deploymentChainId = deployment.chainId ?? 31337;
