# syntax=docker/dockerfile:1.19
# ---------------------------------------------------------------------------
# Indexer: Ponder 0.17 reading the AuctionHouse and DemoNFT logs.
#
# This image contains the indexer ONLY. It has no Solidity toolchain and it
# does not read contracts/artifacts, because indexer/abis/ carries its own
# trimmed copy of the two ABIs. A contract change therefore does not rebuild
# this image; a change to indexer/ does.
#
# It does, however, READ contracts/deployments/31337.json at run time, to learn
# which addresses to watch. That file is generated by the deployer and it is
# supplied through a shared volume, not baked in -- see compose.indexer.yaml.
# A baked-in address would be wrong the moment anything deploys at a different
# nonce.
#
# `ponder start` compiles ponder.config.ts and src/ with esbuild at start-up,
# so there is no build step to run here and no dist/ to copy. That is why the
# runtime stage copies TypeScript sources directly.
# ---------------------------------------------------------------------------

ARG NODE_VERSION=24-alpine

# --- Stage 1: dependencies -------------------------------------------------
FROM node:${NODE_VERSION} AS deps
WORKDIR /opt/auction/indexer

# The manifests only, so this layer stays cached until a dependency changes.
#
# NOTE the paths: the build context is the REPOSITORY ROOT, the same as every
# other image here, because .dockerignore only applies at the context root.
# indexer/ is a standalone package with its own lock file, so the root
# package-lock.json is deliberately not copied.
COPY indexer/package.json indexer/package-lock.json ./

# `npm ci` installs the exact locked versions. Never `npm install` here.
# `--omit=dev` drops typescript and @types/node: `ponder start` bundles with
# esbuild, which strips types without ever type checking, so the compiler is a
# development tool only. The cache mount keeps the npm cache out of the layer.
RUN --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev --no-audit --no-fund

# --- Stage 2: runtime ------------------------------------------------------
FROM node:${NODE_VERSION} AS runtime

LABEL org.opencontainers.image.title="auction-indexer" \
      org.opencontainers.image.description="Ponder indexer for the NFT auction demonstration. Serves GraphQL, SQL over HTTP and a small REST layer." \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="decentralised-auction" \
      org.opencontainers.image.source="https://github.com/prpawan03/decentralised_auction" \
      org.opencontainers.image.base.name="docker.io/library/node:24-alpine"

ENV NODE_ENV=production \
    PONDER_PORT=42069 \
    PONDER_LOG_LEVEL=info \
    npm_config_update_notifier=false

WORKDIR /opt/auction/indexer

# Set ownership DURING the copy.
#
# A separate `RUN chown -R node:node` over node_modules costs minutes and
# writes a second full copy of every file into a new layer. This was measured
# in this repository: the recursive form took 426 seconds in the deployer
# image. `COPY --chown` does the same work for free.
COPY --from=deps --chown=node:node /opt/auction/indexer/node_modules ./node_modules

# The sources. Ponder reads tsconfig.json at start-up to resolve the project,
# so it is not optional here.
COPY --chown=node:node indexer/package.json indexer/tsconfig.json ./
COPY --chown=node:node indexer/ponder.config.ts indexer/ponder.schema.ts ./
COPY --chown=node:node indexer/ponder-env.d.ts ./
COPY --chown=node:node indexer/abis ./abis
COPY --chown=node:node indexer/src ./src

# The probe replaces curl, which the alpine image does not contain. `--chmod`
# sets the executable bit here, so the Git setting on the host does not matter.
# Windows Git does not keep that bit.
COPY --chown=node:node --chmod=0755 indexer/healthcheck.js ./healthcheck.js

# Two directories that are written to, or mounted over, at run time.
#
#   .ponder     Ponder's own scratch space: the build cache and, when
#               DATABASE_URL is unset, the embedded PGlite store.
#   ../contracts/deployments
#               The mount point for the deployment record. It MUST exist and
#               be owned by `node` before the volume is attached, because
#               Docker seeds a fresh named volume from the image's directory,
#               ownership included. Without this the indexer would be handed a
#               root-owned directory it cannot read as a non-root user.
#
# Neither chown is recursive, so both stay fast.
RUN mkdir -p /opt/auction/indexer/.ponder /opt/auction/contracts/deployments \
 && chown node:node /opt/auction /opt/auction/contracts /opt/auction/contracts/deployments \
                    /opt/auction/indexer /opt/auction/indexer/.ponder

# Run as a non-root user.
USER node

EXPOSE 42069

# `/ready` is the right probe, not `/health`.
#
# `/health` answers 200 as soon as the process is up, including for the whole
# of the historical backfill, so a container gated on it would be reported
# healthy while it still had nothing to serve. `/ready` answers 503 until the
# indexing run has caught up to the chain head. The start period is generous
# for exactly that reason: a cold backfill over a seeded demo chain is the
# normal case, not a fault.
HEALTHCHECK --interval=10s --timeout=5s --start-period=90s --retries=12 \
    CMD ["node", "/opt/auction/indexer/healthcheck.js"]

# `ponder start` is the production command: it indexes and serves, and it does
# not watch files. `ponder dev` is for a host checkout.
#
# The hostname is set explicitly. It already defaults to 0.0.0.0, but a default
# that changes turns this container into one that listens only on loopback and
# is unreachable from nginx, which is a confusing failure to diagnose.
CMD ["npx", "ponder", "start", "--hostname", "0.0.0.0", "--port", "42069"]
